plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin-bundle:7.2.3'
    implementation 'org.postgresql:postgresql:42.7.13'
}

sourceSets {
    main {
        java {
            srcDirs = ['jav']
        }
    }
}

application {
    mainClass = 'org.example.Main'
}